### ISSUE TITLE
Importing as ES Module

### ISSUE THREAD

**Issue by josephm1** [FranckFreiburger/vue3-sfc-loader#10]
**Is your feature request related to a problem? Please describe.**
Currently to use vue3-sfc-loader it must be  injected in the global namespace and is not possible to load it is as an es module.

**Describe the solution you'd like**
I'd like to be able to import as an es module with loadModule being the default export (perhaps have version as a named export only), Vue 3 itself already supports being loaded as an es module, and perhaps include a default options so it becomes optional.
**Describe alternatives you've considered**

**Additional context**
I believe that an issue that may come up to support this (I am still new to Vue 3 , so take with a grain of salt), Vue 3 doesn't export a default "Vue"component like previous 2.x esm versions  it only has named exports, this could affect
```javascript
 moduleCache: {
        vue: Vue,
    }
```

If I have misunderstood anything please let me know, thanks again!

**Comment by Toilal** [comment]
webpack now supports ESModule with [libraryTarget: 'module' ](https://webpack.js.org/configuration/output/#librarytarget-module), but it's still experimental.

@FranckFreiburger do you think it could work with webpack, or we should go with rollup ?

**Comment by FranckFreiburger** [comment]
Let's give a try to `libraryTarget: 'module'`. I'm not comfortable enough with rollup.

**Comment by FranckFreiburger** [comment]
https://github.com/FranckFreiburger/vue3-sfc-loader/commit/2cbe3e5f562ad08167f92fd2f1d4c4976feaa5b7

**Comment by FranckFreiburger** [comment]
fixed in https://github.com/FranckFreiburger/vue3-sfc-loader/commit/cd98dd8e2ba527ce2a794d919f7e04d114145685
