### ISSUE TITLE
Does sass/scss work with this yet?

### ISSUE THREAD

**Issue by spburden** [FranckFreiburger/vue3-sfc-loader#104]

**Comment by jeryqwq** [comment]
![image](https://user-images.githubusercontent.com/25569373/148400331-0c345fb1-078d-4e74-9114-72b7c3568641.png)

when i use lang="scss", exec here the source is become empty string, it should be my scss string

**Comment by jeryqwq** [comment]
the file type .scss can take effect , but in vue file , it  is wrong like above image

**Comment by jeryqwq** [comment]
It is work , add sass Obj in your moduleCache, demo here https://github.com/jeryqwq/materialPlatformDemo/blob/master/index.html,
i think i can add a document demo for scss and less
```js
      sass: { async renderSync({data}){
          return new Promise((reslove, reject) => {
            sass.compile(data, function(result) {
              options.addStyle(result.text);
              reslove(result)
            });
          })
        } }
```

**Comment by jeryqwq** [comment]
![image](https://user-images.githubusercontent.com/25569373/148412712-042db69e-02dc-4359-a54c-952c7117dedc.png)


method load('scss') return your moduleCache,  then exec renderSync method for return you result
