### ISSUE TITLE
Adding SFC minifcation/obfuscation

### ISSUE THREAD

**Issue by trekze** [FranckFreiburger/vue3-sfc-loader#119]
Hey Franck

Great library. I've been using it for a while. I like not having a compilation step / webpack.

I was wondering if you've tried adding minification/obfuscation of the SFC files somehow. I know that's not within the scope of what your library should do, but curious if you've come across a tool that can fit in to the picture.

Thanks and keep up the great work.

**Comment by FranckFreiburger** [comment]
unfortunately it's out of the scope of this library
