### ISSUE TITLE
Disabled vue3-sfc-loader cache

### ISSUE THREAD

**Issue by flagellarmirror** [FranckFreiburger/vue3-sfc-loader#122]
Hi,
is it possible to disable the cache of vue3-sfc-loader? I need it because every time I change vue components the only way I have to see the changes is to clear the cache. When I was using httpvueloader I had solved it by adding a timestamp as a query string when importing a component, is it possible to do that again?

**Comment by GodsVictory** [comment]
how do you get this working? I'm facing the same issue

**Comment by dizheyoulan** [comment]
> how did you get this working? I'm facing the same issue

in options Object  ,add`    pathResolve(res){
        return res.relPath+'?'+Date.parse( new Date() ).toString()
    }`

**Comment by dizheyoulan** [comment]
> how did you get this working? I'm facing the same issue

edit options.getFile
`const options = {
    moduleCache: { vue: Vue },
    async getFile(url) {
        const res = await fetch(url+'?'+Date.parse( new Date() ).toString());
        if (!res.ok)throw Object.assign(new Error(res.statusText + ' ' + url), { res });
        return {
            getContentData: asBinary => asBinary ? res.arrayBuffer() : res.text(),
        }
    },
    addStyle(textContent) {
        const style = Object.assign(document.createElement('style'), { textContent });
        const ref = document.head.getElementsByTagName('style')[0] || null;
        document.head.insertBefore(style, ref);
    },
}

const { loadModule } = window['vue3-sfc-loader'];`
