### ISSUE TITLE
Breakpoints

### ISSUE THREAD

**Issue by leecbryant** [FranckFreiburger/vue3-sfc-loader#123]
Is it, currently, possible to add breakpoints in Dev Tools - like pure HTML/JS? If not, is it possible to add them in code?

Finally, if neither are possible, will this be a feature in the future?

**Comment by btsimonh** [comment]
this worked REALLY well with html-vue-loader..  not sure why the vm displays this one all on one line?

**Comment by Hoshinokoe** [comment]
still no way to debug normal code (not a single line) ?

**Comment by FranckFreiburger** [comment]
I plan to add a `devMode : boolean` option that will preserve, as far as possible, the originale script formating.
