### ISSUE TITLE
Example with imported JSON 

### ISSUE THREAD

**Issue by paul-hammant** [FranckFreiburger/vue3-sfc-loader#124]
**Is your feature request related to a problem? Please describe.**

i have looked through the examples and can't see the necessary options{} magic to allow `import data from '/path/to/some.json';` to work.

**Describe the solution you'd like**

Automatic handling of JSON in a vue SFC.  If not automatic, then the functions to add to options{}

**Describe alternatives you've considered**

**Additional context**

**Comment by FranckFreiburger** [comment]
Hi Paul, you just need to define a JSON handler in your `options.handleModule`

```
async handleModule(type, getContentData, path, options) {
  
  if ( type === '.json' )
    return JSON.parse(await getContentData(false));
},
```
