### ISSUE TITLE
 This file  vue3-sfc-loader.js is still very big after gzip compression, which affects the speed. How to optimize it?

### ISSUE THREAD

**Issue by wall-git** [FranckFreiburger/vue3-sfc-loader#13]
It takes a long time to use on the mobile phone~  thanks ^_^

**Comment by FranckFreiburger** [comment]
babel uses 46% of the package (see https://unpkg.com/vue3-sfc-loader/dist/report.html).
https://stackoverflow.com/questions/65304252/use-babel-source-instead-of-babel-packages-babel is an attempt to reduce `vue3-sfc-loader.js` size

**Comment by wall-git** [comment]
> babel uses 46% of the package (see https://unpkg.com/vue3-sfc-loader/dist/report.html "Stat" tab).
> https://stackoverflow.com/questions/65304252/use-babel-source-instead-of-babel-packages-babel is an attempt to reduce `vue3-sfc-loader.js` size

thanks
