### ISSUE TITLE
router-link

### ISSUE THREAD

**Issue by ariden83** [FranckFreiburger/vue3-sfc-loader#130]
Can you make an example using router-link and i18n svp 

in a view : 
```
 <div class="mt-auto">
            <router-link class="btn btn-primary" v-bind:to="'/currencies/' + item.slug" v-bind:title="item.name + 'Charts'">View Charts</router-link>
          </div>
```

**Comment by FranckFreiburger** [comment]
see. https://github.com/FranckFreiburger/vue3-sfc-loader/discussions/172
see. https://github.com/FranckFreiburger/vue3-sfc-loader/blob/main/docs/examples.md#use-sfc-custom-blocks-for-i18n
