### ISSUE TITLE
Any plans on reducing the bundle size?

### ISSUE THREAD

**Issue by trekze** [FranckFreiburger/vue3-sfc-loader#138]
I enjoy using sfc-loader instead of a traditional bundling step for vue. I even use it in production. I do feel slightly guilty due to the package size though. it's the biggest component in my web app despite doing the least (no offence). And I know babel is a big part of it. Any tips or plans on reducing the size? 

Thanks for your great work

**Comment by oceangravity** [comment]
+1

**Comment by Listen-to-poetry-in-the-wind** [comment]
+1

**Comment by FranckFreiburger** [comment]
https://github.com/FranckFreiburger/vue3-sfc-loader/blob/main/docs/faq.md#why-vue3-sfc-loader-is-so-big
