### ISSUE TITLE
 I encountered a bug  when using import default

### ISSUE THREAD

**Issue by huangbaihei** [FranckFreiburger/vue3-sfc-loader#140]
When I use import dayjs from "dayjs", the dayjs I get is not the default export, but the whole module. Dayjs has been put into modulecache

**Comment by FranckFreiburger** [comment]
include the `dayjs` library in the global
```
  <script src="https://cdn.jsdelivr.net/npm/dayjs@1/dayjs.min.js"></script>
```

add `dayjs` library to the `moduleCache`
```
const options = {
  moduleCache: {
    vue: Vue,
    dayjs
  },
  ...
```

use the `dayjs` in your component
```
<script>
  import dayjs from 'dayjs'
  alert(dayjs().format())
</script>
```

**Comment by FranckFreiburger** [comment]
request to be reopened as needed
