### ISSUE TITLE
 http-vue-loader vs  vue3-sfc-loader

### ISSUE THREAD

**Issue by bufferUnderrun** [FranckFreiburger/vue3-sfc-loader#141]
Hi,

Using http-vue-loader since 3 years, it works at best and i'm migrating to vue2-sfc-loader.

But surprisingly : 

- http-vue-loader v1.4.2 : 6Ko (min)
- vue2-sfc-loader v0.8.4 : 2248Ko (min)

I can not use a 2Mo javascript just to load vue component !!

**Why a such enormous size difference ??**

Thanks for your answer

**Comment by FranckFreiburger** [comment]
see https://github.com/FranckFreiburger/vue3-sfc-loader/blob/main/docs/faq.md#why-vue3-sfc-loader-is-so-big
