### ISSUE TITLE
The giving example using a wrong format to call "createCJSModule"

### ISSUE THREAD

**Issue by capraynor** [FranckFreiburger/vue3-sfc-loader#145]
https://github.com/FranckFreiburger/vue3-sfc-loader/blob/80f10f9fd82d7dde6c8681d23d36e9ac3ab9a654/docs/faq.md?plain=1#L122

👆 This line, calling `createCJSModule`, the first parameter should be `path` or something, should not `type`. 

![image](https://user-images.githubusercontent.com/3467515/180741141-17c3c67d-4507-486e-a55c-ce1900a2be85.png)

**Comment by FranckFreiburger** [comment]
Thanks for pointing this out !
