### ISSUE TITLE
Native Components will throw an warning and probably not work

### ISSUE THREAD

**Issue by lfmunoz** [FranckFreiburger/vue3-sfc-loader#158]
Trying to use : https://www.webcomponents.org/element/@alenaksu/json-viewer

but getting the following warning:

```
[vue warn]: Failed to resolve component: json-viewer
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
  at <Anonymous> 
  at <AsyncComponentWrapper> 
  at <Anonymous> 
  at <AsyncComponentWrapper> 
  at <App>
```

There is no way to pass the compiler option?

https://vuejs.org/api/application.html#app-config-compileroptions

```
app.config.compilerOptions.isCustomElement = (tag) => {
    if(tag == 'json-viewer') return true
    return false
  }
```

**Comment by FranckFreiburger** [comment]
Hi lfmunoz, I will add a new `isCustomElement` option.

**Comment by FranckFreiburger** [comment]
BTW, note that app.config.compilerOptions only works in full build (see https://vuejs.org/api/application.html#app-config-compileroptions)

**Comment by lfmunoz** [comment]
Thanks you isCustomElement in compilerOptions is working for me.
