### ISSUE TITLE
Sample not works

### ISSUE THREAD

**Issue by mirshahreza** [FranckFreiburger/vue3-sfc-loader#166]
**I made a sample here but not works, can anyone correct the code?**

The sample is here

https://stackblitz.com/edit/web-platform-qkmnd5?file=index.html

**Comment by fushengruomengzhang** [comment]
<img width="1380" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/63709269/c54d725b-77b6-433d-a2bf-33c6ee6ccb3e">

is ok,no error

**Comment by fushengruomengzhang** [comment]
<img width="1416" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/63709269/9940a98b-225e-4093-8b88-3ddc01c23e84">
Routing Problem

**Comment by mirshahreza** [comment]
Hi again
I make a simple example that is working but the main problem is adding dynamically registered ".vue" component to the page.
Can you have a look 
https://github.com/mirshahreza/DynamicVueComponen

Thanks

**Comment by mirshahreza** [comment]
Because this is not a bug I close this issue and I create a test here:

https://stackoverflow.com/questions/77139424/dynamically-adding-new-vue-component

**Comment by fushengruomengzhang** [comment]
> 因为这不是一个错误，所以我关闭了这个问题并在此处创建了一个测试：
> 
> https://stackoverflow.com/questions/77139424/dynamically-adding-new-vue-component

Using relative paths；

<img width="992" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/63709269/cb52185c-3c8f-45b4-b3a3-92876de10302">
<img width="730" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/63709269/f6d177fd-8b26-4df4-bd77-d73300d4d4ba">
<img width="855" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/63709269/041b934a-baa9-482f-b46f-9719409c568e">

**Comment by mirshahreza** [comment]
It is clear now
Thank you for your time
Regards
