### ISSUE TITLE
defineOptions() not working, resulting in a warning

### ISSUE THREAD

**Issue by Connum** [FranckFreiburger/vue3-sfc-loader#169]
**Describe the bug**

When the SFC uses `defineOptions()` in its setup script, this will result in the following warning:
> VM1252:3 [Vue warn]: defineOptions() is a compiler-hint helper that is only usable inside <script setup> of a single file component. Its arguments should be compiled away and passing it at runtime has no effect.

The options will not be available on the compiled component.

**To Reproduce**

Load an SFC file that uses `defineOptions()` in its setup script.

**Expected behavior**

Component loads without warning and the options are available as properties on the compiled component's object.

**Versions**
 - Browser (name & version): any
 - vue3-sfc-loader: 0.8.4

**Additional context**

\-

**Comment by FranckFreiburger** [comment]
Hi, Connum, this will be fixed in the next release.
