### ISSUE TITLE
Typo in README ?

### ISSUE THREAD

**Issue by raphael-bresson** [FranckFreiburger/vue3-sfc-loader#17]
Hi again Franck,

unless I'm missing something, the end of your README about scoped slots

```
<context-menu ref="menu">
  <template scope="child">
    <li @click="onClick('A', child.userData)">Option A</li>
    <li @click="onClick('B', child.userData)">Option B</li>
  </template>
</context-menu>
```

should read

`  <template v-slot="child">`

No ?

**Comment by FranckFreiburger** [comment]
raphael-bresson, if you encounter an issue/mistake in the documentation, feel free to create a new pull request.
