### ISSUE TITLE
vue3-sfc-loader.esm.js should expose the vue is has embedded 

### ISSUE THREAD

**Issue by lfmunoz** [FranckFreiburger/vue3-sfc-loader#177]
My code looks like this:

```js
import * as Vue from '../js_ext/vue.js'
console.log(`vue.js version ${Vue.version}`)    <-----  3.3.4

import { loadModule, vueVersion } from '../js_ext/vue3-sfc-loader.esm.js'
console.log(`vu3-sfc-loader vue version ${vueVersion} `)   <-----  3.4.5 
```

The issue is I have to import Vue twice. 

vue3-sfc-loader.esm.js  has it's own internal Vue so it needs to expose that. the solution should allow for the following:

```js
import { loadModule, vueVersion, Vue } from '../js_ext/vue3-sfc-loader.esm.js'
console.log(`vue.js version ${Vue.version}`)    <-----  3.4.5
```

**Comment by lfmunoz** [comment]
I'm probably mistaken about this seem like only @vue/compiler-sfc is included in vue3-sfc-loader.esm.js  and doesn't include the runtime.  Please go ahead and close if that is the case.

**Comment by FranckFreiburger** [comment]
lfmunoz, you are true, vue3-sfc-loader only embeds the vue compiler, and expose its version in `vueVersion`
