### ISSUE TITLE
Query Strings in module filepath are treated as part of the exension

### ISSUE THREAD

**Issue by BenWoodford** [FranckFreiburger/vue3-sfc-loader#182]
**Describe the bug**

If you try to load a module at say... "component.vue?date=2024.02.04" for cache-busting reasons it will fail, as the loader will assume the extension is ".04" not" .vue".

**To Reproduce**
See above

**Expected behavior**
The loader should ignore anything after (and including) a "?"

**Versions**
 - vue3-sfc-loader:  0.8.4

**Comment by FranckFreiburger** [comment]
additionally, `/main.vue?a=/foo` will also fail because `Path.dirname('/main.vue?a=/foo')` returns `/main.vue?a=` instead of `/`
