### ISSUE TITLE
使用问题反馈

### ISSUE THREAD

**Issue by hzdjulytech** [FranckFreiburger/vue3-sfc-loader#188]
```
  <script type="importmap">
  {
    "imports": {
      "axios": "https://unpkg.com/axios@1.6.8/dist/esm/axios.js" ,
	  "vue":"https://unpkg.com/vue@3.4.21/dist/vue.esm-browser.js",
	  "vue-router":"https://unpkg.com/vue-router@4.3.0/dist/vue-router.esm-browser.js"
    }
  }
</script>
```
首选出问题的是 vue-router.esm-browser.js 中导入了@vue/devtools-api
添加了 ` "@vue/devtools-api":"https://unpkg.com/@vue/devtools-api@6.6.1/lib/esm/index.js"`
或者将 相关文件复制到后端资源目录 
![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/00ba3fca-357e-481b-b55c-5d265d2a5ee7)
这时候出现了第二个问题 相对路径错误 
![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/bcccd5c9-0e9d-487b-b6b9-a786b8628ea3)
![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/5fdbaade-2d88-4454-86b3-a92e17ec108e)
![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/e0e39116-e1ff-4084-87b1-1faeee457056)

![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/d4bf778b-ade7-4415-8e83-2d38e31beb79)

前端开发导入时 一般习惯省略后缀 或者 index.xx 这会导致相对路径错误 ，真实路径只有相关服务器知道 应该有个方式告诉
vue3-sfc-loader 其内部资源加载相对路径以什么为准

**Comment by FranckFreiburger** [comment]
please use English language only.

**Comment by hzdjulytech** [comment]
![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/be6fa12b-59a6-4d4c-a511-12176737c9fb)
 
![image](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/36155555/e8f270d5-7e88-43ca-8a70-bc3818137b7c)
