### ISSUE TITLE
Relative load of child-component has URL issues

### ISSUE THREAD

**Issue by paul-hammant** [FranckFreiburger/vue3-sfc-loader#19]
See https://paulhammant.com/1970/01/01/vue-sfc2/.

Embedded in that page, //raw.githubusercontent.com/paul-hammant/VueSfcDemo/master/comps/calc/Calculator.vue loads just fine.

That SFC component attempts to load ./Display.vue, but that barfs because vue3-sfc-loader is looking at https://paulhammant.com/raw.githubusercontent.com/paul-hammant/VueSfcDemo/master/comps/calc/Display.vue rather than adjacent to Calculator.vue.

**Comment by FranckFreiburger** [comment]
Maybe  https://github.com/FranckFreiburger/vue3-sfc-loader/blob/main/src/index.ts#L465-L471 does not work properly.

**Comment by paul-hammant** [comment]
Could be tricky to solve. Intellectually we know Calc.vue is loading
Display.vue but the underlying framework has no idea about the context
switch.  Maybe an explicitly component path has to be passed it.

**Comment by FranckFreiburger** [comment]
resolvePath("//raw.githubusercontent.com/paul-hammant/VueSfcDemo/master/comps/calc/Calculator.vue", "./Display.vue")
returns
  `"/raw.githubusercontent.com/paul-hammant/VueSfcDemo/master/comps/calc/Display.vue"`
but should return 
  `"//raw.githubusercontent.com/paul-hammant/VueSfcDemo/master/comps/calc/Display.vue"`

**Comment by paul-hammant** [comment]
> this should be doable
Good news.

For fun, and attempt to use fully qualified paths has a very similar error - https://paulhammant.com/1970/01/01/vue-sfc3/ - a single '/' dropped on the child component URL resolution.

**Comment by FranckFreiburger** [comment]
Hi,

I don't want vue3-sfc-loader to handle remote URLs by default. However, I will add a new `pathHandlers` options that will defaults to :

```
import { posix as Path } from 'path'
...
const defaultPathHandlers : PathHandlers = {
	dirname(path) {

		return Path.dirname(path);
	},
	extname(path) {

		return Path.extname(path);
	},
	resolve(current, dep) {

		if ( dep[0] !== '.' )
			return dep;

		return Path.normalize(Path.join(Path.dirname(current), dep));
	}
}
```

**Comment by paul-hammant** [comment]
Cool, thanks

**Comment by FranckFreiburger** [comment]
fixed in v0.3.0

**Comment by paul-hammant** [comment]
Yeah, I'm lost as to how to use this new feature. I've been trying permutations of:

![image](https://user-images.githubusercontent.com/82182/108625344-47007880-73ff-11eb-8cc8-b70eeb6a6f46.png)

but getting nowhere

**Comment by FranckFreiburger** [comment]
Here is the default implementation of `pathHandlers` (when not provided in the `options` argument) : https://github.com/FranckFreiburger/vue3-sfc-loader/blob/4a9e5666efbbb7ca7eaf508269b7d75c36104d0e/src/index.ts#L763-L775

You have to create your own version of `pathHandlers` and provide it in the `options` object.

eg.
```
import { posix as Path } from 'path'

const myPathHandlersThatSupportsURLs = {
	extname(filepath) {

		return Path.extname(new URL(filepath, window.location).pathname);
	},
	resolve(absoluteFilepath, dependencyPath) {

		return String(new URL(dependencyPath, absoluteFilepath));
	}
}
```
:warning: the code above has not been properly tested !

**Comment by FranckFreiburger** [comment]
I'm closing this as answered. Discussion can continue if needed.

**Comment by FranckFreiburger** [comment]
Did you manage to use the above code ?

**Comment by FranckFreiburger** [comment]
see also https://github.com/FranckFreiburger/vue3-sfc-loader/blob/main/docs/examples.md#use-remote-components

**Comment by paul-hammant** [comment]
I tried and couldn't get it working. Then put it on my todo list, then
never circled back. sorry Frank - this is important so I'll have another go
on Sunday when Ihave free time. Thanks for doing the work.

**Comment by paul-hammant** [comment]
Oh this looks exciting - https://github.com/FranckFreiburger/vue3-sfc-loader/blob/main/docs/examples.md .... examples source and links to standalone proofs in JsBin - great work, Franck!

**Comment by paul-hammant** [comment]
I circled back and incorporated the suggested functions: https://paulhammant.com/2021/02/16/buildless-sfc-vuejs-applications/ - all working now. I might also take advantage of the hot interception of library loading (velocity in my case)

Great work Franck.

- Paul
