### ISSUE TITLE
Error after load vue3-sfc-loader  locally

### ISSUE THREAD

**Issue by dreambo8563** [FranckFreiburger/vue3-sfc-loader#190]
**Describe the bug**

I download the vue3-sfc-loader.js on my local, and run a web server to produce the demo. failed with errors
**To Reproduce**

1. download the file with curl:
`curl https://cdn.jsdelivr.net/npm/vue3-sfc-loader/dist/vue3-sfc-loader.js -o vue3-sfc-loader.js`
2. copy the demo code from codepen (https://codepen.io/franckfreiburger/project/editor/AqPyBr)
3. run a webserver
`python3 -m http.server 8080`
4. load the page with error :
<img width="946" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/6948318/93fcbed6-4db8-4040-89db-938c7cb80aec">
the error navigate to a block of strange code 
<img width="561" alt="image" src="https://github.com/FranckFreiburger/vue3-sfc-loader/assets/6948318/2c614690-ad7e-4c49-be64-707ce57f3260">

**Expected behavior**

no error happen and I can make the demo successfully .

**Versions**
 - Browser (name & version): Chrome Version 123.0.6312.122 (Official Build) (x86_64)
 - vue3-sfc-loader: v0.9.5

**Additional context**

when load the js with CDN as the document write, everything works, I don't know which step make the error happen and what the difference between the file I downloaded and the file on CDN server.

**Comment by tucker87** [comment]
Looks to be an encoding issue.

I donloaded the file and found the line in question. This is properly formatted in the file.

```js
{À:"A",Á:"A",Â:"A",Ã:"A",Ä:"A",Å:"A",à:"a",á:"a",â:"a",ã:"a",ä:"a",å:"a",Ç:"C",ç:"c",Ð:"D",ð:"d",È:"E",É:"E",Ê:"E",Ë:"E",è:"e",é:"e",ê:"e",ë:"e",Ì:"I",Í:"I",Î:"I",Ï:"I",ì:"i",í:"i",î:"i",ï:"i",Ñ:"N",ñ:"n",Ò:"O",Ó:"O",Ô:"O",Õ:"O",Ö:"O",Ø:"O",ò:"o",ó:"o",ô:"o",õ:"o",ö:"o",ø:"o",Ù:"U",Ú:"U",Û:"U",Ü:"U",ù:"u",ú:"u",û:"u",ü:"u",Ý:"Y",ý:"y",ÿ:"y",Æ:"Ae",æ:"ae",Þ:"Th",þ:"th",ß:"ss",Ā:"A",Ă:"A",Ą:"A",ā:"a",ă:"a",ą:"a",Ć:"C",Ĉ:"C",Ċ:"C",Č:"C",ć:"c",ĉ:"c",ċ:"c",č:"c",Ď:"D",Đ:"D",ď:"d",đ:"d",Ē:"E",Ĕ:"E",Ė:"E",Ę:"E",Ě:"E",ē:"e",ĕ:"e",ė:"e",ę:"e",ě:"e",Ĝ:"G",Ğ:"G",Ġ:"G",Ģ:"G",ĝ:"g",ğ:"g",ġ:"g",ģ:"g",Ĥ:"H",Ħ:"H",ĥ:"h",ħ:"h",Ĩ:"I",Ī:"I",Ĭ:"I",Į:"I",İ:"I",ĩ:"i",ī:"i",ĭ:"i",į:"i",ı:"i",Ĵ:"J",ĵ:"j",Ķ:"K",ķ:"k",ĸ:"k",Ĺ:"L",Ļ:"L",Ľ:"L",Ŀ:"L",Ł:"L",ĺ:"l",ļ:"l",ľ:"l",ŀ:"l",ł:"l",Ń:"N",Ņ:"N",Ň:"N",Ŋ:"N",ń:"n",ņ:"n",ň:"n",ŋ:"n",Ō:"O",Ŏ:"O",Ő:"O",ō:"o",ŏ:"o",ő:"o",Ŕ:"R",Ŗ:"R",Ř:"R",ŕ:"r",ŗ:"r",ř:"r",Ś:"S",Ŝ:"S",Ş:"S",Š:"S",ś:"s",ŝ:"s",ş:"s",š:"s",Ţ:"T",Ť:"T",Ŧ:"T",ţ:"t",ť:"t",ŧ:"t",Ũ:"U",Ū:"U",Ŭ:"U",Ů:"U",Ű:"U",Ų:"U",ũ:"u",ū:"u",ŭ:"u",ů:"u",ű:"u",ų:"u",Ŵ:"W",ŵ:"w",Ŷ:"Y",ŷ:"y",Ÿ:"Y",Ź:"Z",Ż:"Z",Ž:"Z",ź:"z",ż:"z",ž:"z",Ĳ:"IJ",ĳ:"ij",Œ:"Oe",œ:"oe",ŉ:"'n",ſ:"ss"}
```

**Comment by FranckFreiburger** [comment]
Hi dreambo8563,

this part of this file should be:
![image](https://github.com/user-attachments/assets/87257274-5274-4933-af48-819f6d0d031c)

maybe an UTF-8 issue when downloading vue3-sfc-loader.js with curl ?
