### ISSUE TITLE
Browser compatibility seems to have not taken effect after adjusting the configuration

### ISSUE THREAD

**Issue by wsqrin** [FranckFreiburger/vue3-sfc-loader#192]
Hello sir
After adjusting the browserslist multiple times in the package.json file and using the build web command to package it, the size of the generated vue3-sfc-loader.js remained unchanged and remained at 1796KB. I don't know if my configuration hasn't taken effect.
I need to be able to run it on Google 70 version, and in version 0.8, I made similar configurations and packaged it to run on Google 58 version.

I have been running your work in a production environment for over 3 years. In the past, some users were unable to use their phones due to browser compatibility issues. Therefore, if I want to upgrade now, I need to solve compatibility issues. Thank you.

package.json configuration:
{
  "browserslist": "> 0.5%, last 2 versions, Firefox ESR, not dead, ie >= 10, chrome >= 58",
}

![img2024-04-28-001](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/44998695/f20bcb0c-5c25-42cb-a17b-d0c151b63856)
![img2024-04-28-002](https://github.com/FranckFreiburger/vue3-sfc-loader/assets/44998695/42e6b6b0-06e3-442c-8701-57b154ca45dc)

**Comment by FranckFreiburger** [comment]
Hi wsqrin,
I was wondering what the problem was and how you solved it ?
