### ISSUE TITLE
Create modules from strings

### ISSUE THREAD

**Issue by maximdeclercq** [FranckFreiburger/vue3-sfc-loader#2]
**Describe the bug**
The examples show that we can use createSFCModule, however I'm only able to use loadModule.

**To Reproduce**
1. Add the latest `vue3-sfc-loader` to the `<head>`.
2. Add a script tag with `const { createSFCModule } = window["vue3-sfc-loader"];`
3. Try to use the function.
4. See the error (createSFCModule is undefined):
`Uncaught TypeError: createSFCModule is not a function`

**Expected behavior**
`createSFCModule` should create a new component from a single file component source string.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: 83

**Comment by FranckFreiburger** [comment]
My bad, the example is out of date, use this meanwhile : https://codepen.io/franckfreiburger/project/editor/AqPyBr

**Comment by maximdeclercq** [comment]
Is it possible to parse template source code that's inside a variable? Because I'd need this for my project.

**Comment by FranckFreiburger** [comment]
https://github.com/FranckFreiburger/vue3-sfc-loader#using-another-template-language-pug show you how to define your own `getFile()`

**Comment by maximdeclercq** [comment]
Oh I see, thank you! I think I will create a dictionary with the sources then.

**Comment by maximdeclercq** [comment]
I'm having the following issue when trying this with the code below:

```javascript
const { loadModule } = window["vue3-sfc-loader"];
            
const TestTextComponent = Vue.defineAsyncComponent(() => loadModule("TestTextComponent.vue", {
    moduleCache: {
        vue: Vue,
    },
    getFile() {
        return Promise.resolve(`
            <template>
                <div class="example">[[ msg ]]</div>
            </template>
            <script>
                export default {
                    data() {
                        return {
                            msg: Hello World
                        }
                    }
                }
            <\/script>
            <style scoped>
                .example {
                    color: red;
                }
            </style>
        `)
    },
}))
```

But unfortunately, I am getting the following error:
![Error](https://i.imgur.com/8Zj6GJX.png)

**Comment by FranckFreiburger** [comment]
please fix:
- <div class="example">[[ msg ]]</div>
- msg: Hello World

BTW, you can avoid escaping html in JS string using the following hack: myString = /**/

**Comment by maximdeclercq** [comment]
Oh, I'm sorry about the string msg, my bad.  About the brackets, I've overridden the delimiters for Vue so that should be correct for my Vue instance (is there any support for this?). Thanks a lot!

**Comment by FranckFreiburger** [comment]
It seems that delimiters are also be redefined in Vue3: https://v3.vuejs.org/api/options-misc.html#delimiters

**Comment by maximdeclercq** [comment]
Jep correct that's how I've done it (but I've managed to use curly braces right now).

However, the below code is still not working sadly enough.
```javascript
const { loadModule } = window["vue3-sfc-loader"];

const TestTextComponent = Vue.defineAsyncComponent(() => loadModule("TestTextComponent.vue", {
    moduleCache: {
        vue: Vue,
    },
    getFile(url) {
        return Promise.resolve( /*<!--*/ `
                <template>
                    <div class="example">{{ msg }}</div>
                </template>
                <script>
                export default {
                    data() {
                        return {
                            msg: "Hello world"
                        }
                    }
                }
                </script>
                <style scoped>
                .example {
                    color: red;
                }
                </style>
` /*-->*/ )
    },
}))
```

![Error](https://i.imgur.com/TC1SsGD.png)

**Comment by FranckFreiburger** [comment]
I agree that the error message is not clear ;)
`options.addStyle()` is not optional

**Comment by maximdeclercq** [comment]
> I agree that the error message is not clear ;)
> `options.addStyle()` is not optional

Ah thanks, can you correct this example or make it optional? https://github.com/FranckFreiburger/vue3-sfc-loader#using-another-template-language-pug.

**Comment by FranckFreiburger** [comment]
In order to avoid new issues like "my styles do not work" I will definitively keep `addStyle()` mandatory but the error will be clearer.
BTW, you can define `addStyle` with `() => {}`
