### ISSUE TITLE
SharedArrayBuffer will require cross-origin isolation as of M91

### ISSUE THREAD

**Issue by kempcalalo** [FranckFreiburger/vue3-sfc-loader#53]
**Describe the bug**
I am using vue2-sfc-loader but I got this warning on chrome console.

vue2-sfc-loader.js:59 [Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.

**To Reproduce**
Reference vue2-sfc-loader

**Expected behavior**

No warning should be displayed.

**Versions**
 - Microsoft Edge: Version 89.0.774.75 (Official build) (64-bit)
 - vue2-sfc-loader:

**Additional context**
![image](https://user-images.githubusercontent.com/17131957/115237239-a2f42e80-a11c-11eb-9dbb-e0f78135620b.png)

**Comment by horidream** [comment]
For now I use the workaround 

```js
const isEnabledSharedArrayBuffer =
  typeof SharedArrayBuffer === "function" &&
  typeof window !== "undefined" &&
  global.crossOriginIsolated === true;
if (!isEnabledSharedArrayBuffer) {
  global.SharedArrayBuffer = ArrayBuffer;
}
```

**Comment by FranckFreiburger** [comment]
waiting for this PR : https://github.com/browserify/node-util/pull/59
