### ISSUE TITLE
Can't build using vue2-sfc-loader ESM with rollup/vite

### ISSUE THREAD

**Issue by Toilal** [FranckFreiburger/vue3-sfc-loader#67]
**Describe the bug**

I try to build an app using vue2-sfc-loader (esm) and vite.

It works properly in dev mode, but when building the app, it fails. Vite is building with rollup under the hood, so it may likely be a configuration issue, but I can't understand the following error.

```
[commonjs] Unexpected token (15:124277) in /home/toilal/projects/OFB-ESTAMP/frontend-vite/node_modules/vue3-sfc-loader/dist/vue2-sfc-loader.esm.js
```

**To Reproduce**

**Expected behavior**

**Versions**
 - Browser (name & version):
 - vue2-sfc-loader: v0.7.3

**Additional context**

**Comment by FranckFreiburger** [comment]
using the dev version of `vue3-sfc-loader` :

```
  loc: {
    file: '...vue2-sfc-loader.esm.js',
    line: 76715,
    column: 11
  },
  frame: "76713: process.title = 'browser';\n" +
    '76714: process.browser = true;\n' +
    '76715: process.env = {};\n' +
    '                  ^\n' +
    '76716: process.argv = [];\n' +
    "76717: process.version = ''; // empty string to avoid regexp issues",
```

**Comment by Toilal** [comment]
It doesn't seems to be related to process.env, but more likely a statement that rollup can't parse from the distribution bundle file.

```javascript
{return(t?i.default.statement`
        EXPORTS.__esModule = true;
      `:i.default.statement`
        Object.defineProperty(EXPORTS, "__esModule", {
          value: true,
        });
      `)({EXPORTS:e.exportName})}
```

**Comment by Toilal** [comment]
I tried to build from current master, and it seems it fixe the issue. Can you release a new version ?

**Comment by FranckFreiburger** [comment]
version 0.8.0 has been released.

however, note that "generate TypeScript definition file as a bundle" feature has been temporary disabled because of https://github.com/FranckFreiburger/vue3-sfc-loader/pull/65#issuecomment-841708263

**Comment by FranckFreiburger** [comment]
> I tried to build from current master, and it seems it fixe the issue. Can you release a new version ?

Can I close this issue ?

**Comment by Toilal** [comment]
Yes, it works now ! Thanks
