### ISSUE TITLE
Poor compatibility of v0.8.0 version

### ISSUE THREAD

**Issue by gao2009ss** [FranckFreiburger/vue3-sfc-loader#81]
Poor compatibility of v0.8.0 version

------------------------------------
v0.7.3

Chromium ：69.0.3497.81  compatible
Firefox ：  59.0.1     compatible

-----------------------------------------
v0.8.0

Chromium ：69.0.3497.81  Not compatible
Firefox ：  59.0.1    Not compatible

error
Uncaught SyntaxError: Unexpected token 
Uncaught TypeError: Cannot destructure property `loadModule` of 'undefined' or 'null'.

**Comment by FranckFreiburger** [comment]
Poor issue description ...

**Comment by gao2009ss** [comment]
![aaaa](https://user-images.githubusercontent.com/29231611/122601215-897f4c80-d0a3-11eb-93fd-940925548696.jpg)

**Comment by FranckFreiburger** [comment]
Please provide a complete example so that I can reproduce the problem.

**Comment by gao2009ss** [comment]
`<html>
<body>
  <div id="app"></div>
  <script src="https://unpkg.com/vue@next"></script>
  <script src="https://cdn.jsdelivr.net/npm/vue3-sfc-loader/dist/vue3-sfc-loader.js"></script>
  <script>

    const options = {
      moduleCache: {
        vue: Vue
      },
      async getFile(url) {
        
        const res = await fetch(url);
        if ( !res.ok )
          throw Object.assign(new Error(res.statusText + ' ' + url), { res });
        return {
          getContentData: asBinary => asBinary ? res.arrayBuffer() : res.text(),
        }
      },
      addStyle(textContent) {

        const style = Object.assign(document.createElement('style'), { textContent });
        const ref = document.head.getElementsByTagName('style')[0] || null;
        document.head.insertBefore(style, ref);
      },
    }

    const { loadModule } = window['vue3-sfc-loader'];

    const app = Vue.createApp({
      components: {
        'my-component': Vue.defineAsyncComponent( () => loadModule('./vue/myComponent.vue', options) )
      },
      template: '<my-component></my-component>'
    });

    app.mount('#app');

  </script>
</body>
</html>`


myComponent.vue
`<template>
  <div>hello {{ name }}</div>
</template>

<script>

export default({
  name: 'MyComponent',
  data() {
    return {
      name: 'hi',
    };
  },
});
</script>`


Browser version: 
Chromium 69.0.3497.81     
Firefox  59.0.1 


vue3-sfc-loader v0.7.3  run successfully
vue3-sfc-loader v0.8.0 run error

**Comment by FranckFreiburger** [comment]
Current browserslist is "> 1%, last 2 versions, Firefox ESR, not dead, not ie 11"
Maybe Chromium 69.0.3497.81 and Firefox 59.0.1 are out of this browserslist range.

You can try to build your own vue3-sfc-loader version with a different browserslist range.
See https://github.com/FranckFreiburger/vue3-sfc-loader#build-your-own-version

**Comment by FranckFreiburger** [comment]
Have you tried to compile your own version of vue3-sfc-loader with a different browserslist range ?

**Comment by FranckFreiburger** [comment]
https://github.com/FranckFreiburger/vue3-sfc-loader/releases/tag/v0.8.4
