### ISSUE TITLE
`n.helpers.keys is not a function or its return value is not iterable`

### ISSUE THREAD

**Issue by hmexx** [FranckFreiburger/vue3-sfc-loader#86]
I had to switch from unpkg to jsdelivr a few seconds ago because the latter was failing for all my users. Have you recently pushed an update? if so jsdelivr might start failing soon as well if it's just on the old one. Please have a look into this! Will try to grab a copy of the current working one.

jsDelivr CDN: https://cdn.jsdelivr.net/npm/vue3-sfc-loader/dist/vue3-sfc-loader.js
UNPKG CDN: https://unpkg.com/vue3-sfc-loader

Error: `n.helpers.keys is not a function or its return value is not iterable`

![image](https://user-images.githubusercontent.com/3520226/123631359-93751e00-d80e-11eb-9d4d-90b971afd18f.png)

**Comment by FranckFreiburger** [comment]
...meanwhile, use the previous version : https://cdn.jsdelivr.net/npm/vue3-sfc-loader@0.8.0/dist/vue3-sfc-loader.js

**Comment by FranckFreiburger** [comment]
please give more details about your browser

**Comment by hmexx** [comment]
Fails on all browsers from what I can see. At least chrome, brave and firefox.

**Comment by FranckFreiburger** [comment]
any minimalist testcase ?

**Comment by hmexx** [comment]
Afraid not. Will have to go back to day-to-day work for now that I can use the old version (thanks for the CDN link). If you're struggling a few days from now, I can try and help out with a test case then.

Keep up the good work.

**Comment by FranckFreiburger** [comment]
`core-js` is polluting `vue3` global scope

**Comment by JamShady** [comment]
Oh my days, I wish I'd checked here earlier. I've literally spent all day on this thinking it was Vue :(

So, just to add:
- Reverting to 0.8.0 works perfectly
- Using the CDN for 0.8.1 and window['vue3-sfc-loader'] also works? It's just pulling it in via package.json (and building with Laravel Mix/Webpack) and require('vue3-sfc-loader') which then causes it to break.

**Comment by FranckFreiburger** [comment]
fixed in https://github.com/FranckFreiburger/vue3-sfc-loader/commit/ca73b8f40321770d3256e565fa5dbc998a5bee5c
